-- Migration 1: Create organizations table
-- This table stores organization/tenant data with settings in JSONB

create table "public"."organizations" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "name" text not null,
  "slug" text not null unique,
  "settings" jsonb not null default '{}',
  "disabled" boolean not null default false,
  "logo_light" jsonb,
  "logo_dark" jsonb,
  PRIMARY KEY (id)
);

-- Index for slug lookups
CREATE INDEX idx_organizations_slug ON organizations(slug);

-- Enable Row Level Security
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;

-- Note: RLS policy will be added after sales.organization_id exists (migration 05)
-- For now, create a permissive policy that will be replaced later
CREATE POLICY "temp_allow_all" ON organizations
  FOR SELECT TO authenticated
  USING (true);

-- Grant permissions
GRANT SELECT ON organizations TO authenticated;

-- Comment the table and key columns
COMMENT ON TABLE organizations IS 'Organizations/tenants table for multi-tenancy support';
COMMENT ON COLUMN organizations.settings IS 'JSONB column storing organization-specific configuration (companySectors, dealCategories, etc.)';
COMMENT ON COLUMN organizations.slug IS 'URL-safe unique identifier for the organization';
