-- Migration: Create API keys table for programmatic access
-- ⚠️ CRITICAL FOR SECURITY - API keys provide authenticated access without user login

-- ========================================
-- API KEYS TABLE
-- ========================================

CREATE TABLE api_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_hash text NOT NULL UNIQUE,
  key_prefix text NOT NULL,
  type text NOT NULL CHECK (type IN ('master', 'organization')),
  organization_id bigint,
  scopes jsonb DEFAULT '["read", "write"]'::jsonb,
  created_by bigint REFERENCES sales(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  last_used_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  name text,

  CONSTRAINT "api_keys_org_fkey"
    FOREIGN KEY (organization_id)
    REFERENCES organizations(id)
    ON DELETE CASCADE,

  CONSTRAINT "master_keys_no_org"
    CHECK (type = 'master' AND organization_id IS NULL OR type != 'master'),

  CONSTRAINT "org_keys_require_org"
    CHECK (type = 'organization' AND organization_id IS NOT NULL OR type != 'organization')
);

-- Indexes for performance
CREATE INDEX idx_api_keys_key_hash ON api_keys(key_hash);
CREATE INDEX idx_api_keys_organization_id ON api_keys(organization_id);
CREATE INDEX idx_api_keys_active ON api_keys(revoked_at) WHERE revoked_at IS NULL;

-- Enable RLS
ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Admins can only see their organization's keys
CREATE POLICY "tenant_isolation_select" ON api_keys
  FOR SELECT TO authenticated
  USING (
    type = 'organization' AND organization_id = get_user_organization_id()
  );

-- INSERT: Admins can create keys for their organization
CREATE POLICY "tenant_isolation_insert" ON api_keys
  FOR INSERT TO authenticated
  WITH CHECK (
    type = 'organization' AND organization_id = get_user_organization_id()
  );

-- UPDATE: Used for revoking keys
CREATE POLICY "tenant_isolation_update" ON api_keys
  FOR UPDATE TO authenticated
  USING (
    type = 'organization' AND organization_id = get_user_organization_id()
  )
  WITH CHECK (
    type = 'organization' AND organization_id = get_user_organization_id()
  );

-- DELETE: Admins can delete their org's keys
CREATE POLICY "tenant_isolation_delete" ON api_keys
  FOR DELETE TO authenticated
  USING (
    type = 'organization' AND organization_id = get_user_organization_id()
  );

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON api_keys TO authenticated;

-- Add comment for documentation
COMMENT ON TABLE api_keys IS 'Stores API keys for programmatic access. Keys are hashed (SHA-256) for security.';
COMMENT ON COLUMN api_keys.key_hash IS 'SHA-256 hash of the API key. Never store plaintext keys.';
COMMENT ON COLUMN api_keys.key_prefix IS 'First 12 characters of the key for display (e.g., "ak_org_abc...").';
COMMENT ON COLUMN api_keys.type IS 'Key type: "master" (super admin) or "organization" (scoped to one org).';
COMMENT ON COLUMN api_keys.scopes IS 'Permissions for the key: ["read"], ["write"], or ["read", "write"].';
